<script setup lang="ts">
const props = defineProps<{
  enabled: boolean
  isLoading: boolean
  onEnable: () => void
  onDisable: () => void
  statusError?: string | null
}>()

const enable = () => {
  if (!props.isLoading) {
    props.onEnable()
  }
}

const disable = () => {
  if (!props.isLoading) {
    props.onDisable()
  }
}
</script>

<template>
  <BaseCard class="flex flex-col gap-6 p-6">
    <div class="flex items-start justify-between gap-4">
      <div>
        <BaseHeading as="h3" size="md" weight="semibold" class="text-muted-900 dark:text-muted-100">
          Two-factor authentication
        </BaseHeading>
        <BaseParagraph size="sm" class="text-muted-500 dark:text-muted-400">
          Protect sign-ins with a time-based code from an authenticator app.
        </BaseParagraph>
      </div>
      <BaseButton
        variant="outline"
        :color="enabled ? 'danger' : 'primary'"
        size="sm"
        :loading="isLoading"
        :disabled="isLoading"
        @click="enabled ? disable() : enable()"
      >
        <Icon :name="enabled ? 'ph:shield-slash' : 'ph:shield-check'" class="size-4" />
        {{ enabled ? 'Disable 2FA' : 'Enable 2FA' }}
      </BaseButton>
    </div>

    <div class="grid gap-4 rounded-2xl border border-muted-200 bg-muted-50/60 p-4 dark:border-muted-800 dark:bg-muted-900/40">
      <div class="flex items-center gap-3">
        <div class="rounded-full bg-info-100 p-2 dark:bg-info-900/40">
          <Icon name="solar:shield-keyhole-linear" class="size-5 text-info-600 dark:text-info-300" />
        </div>
        <div>
          <BaseHeading as="h4" size="xs" weight="medium" class="text-muted-500 dark:text-muted-400">
            Current status
          </BaseHeading>
          <div class="flex items-center gap-2">
            <BaseChip :color="enabled ? 'success' : 'warning'" size="xs">
              {{ enabled ? 'Enabled' : 'Disabled' }}
            </BaseChip>
            <BaseText size="xs" class="text-muted-500 dark:text-muted-400">
              {{ enabled ? 'Autheticator verification required on login.' : 'Turn on TOTP to add an extra security layer.' }}
            </BaseText>
          </div>
        </div>
      </div>

      <div class="flex flex-wrap items-center gap-4">
        <div class="flex items-center gap-2 text-xs text-muted-500 dark:text-muted-400">
          <Icon name="ph:number-circle-one" class="size-4" /> Install an authenticator app.
        </div>
        <div class="flex items-center gap-2 text-xs text-muted-500 dark:text-muted-400">
          <Icon name="ph:number-circle-two" class="size-4" /> Scan the QR code generated by SnapLink.
        </div>
        <div class="flex items-center gap-2 text-xs text-muted-500 dark:text-muted-400">
          <Icon name="ph:number-circle-three" class="size-4" /> Enter the 6-digit code to confirm.
        </div>
      </div>

      <BaseAlert v-if="statusError" color="warning" variant="soft" class="rounded-xl">
        <template #title>Heads up</template>
        <p class="text-sm text-muted-600 dark:text-muted-300">
          {{ statusError }}
        </p>
      </BaseAlert>
    </div>
  </BaseCard>
</template>
